### ISSUE TITLE
v01. Missing Favicon

### ISSUE THREAD

**Issue by Niculina107631** [sebiboga/peviitor#11]
Browser: Chrome
Environment: https://v01.peviitor.ro/
                      https://peviitor.ro

Steps to reproduce:
1. Open https://webpagetest.org/
2. Add URL: https://v01.peviitor.ro/
3. Press Start testing
4. Open Optimization and verify Favicon is added to the checklist

Expected results:
Favicon is added to checklist

Actual results:
Favicon is not implemented
![image](https://user-images.githubusercontent.com/78035628/153258086-f877be3d-7c01-47a4-8b0f-14c3eda06c39.png)

**Comment by sebiboga** [comment]
@sergiuavram please create the image and fix this in V3
I will update the current production version V1

**Comment by Niculina107631** [comment]
@sebiboga please make sure it is deployed on v01 as discussed as well

**Comment by sebiboga** [comment]
@Niculina107631 please retest
